spring:  
  application:
    #name: unieap-common-slave
    name: unieap-common-master
  profiles : 
     #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
     active : dev
#################################################
#应用级别参数
#################################################
  thymeleaf :
    cache: false
    suffix: .html
    encoding: UTF-8
    # 解决中文乱码
    content-type: text/html; charset=utf-8
    #mode=HTML5 not work
    mode: HTML
  jpa :
     database : MYSQL  
     show-sql : false
     open-in-view : false
     # Hibernate ddl auto (create, create-drop, update)
     generate-ddl: false
     hibernate :
       ddl-auto : update
       naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
     properties :
        hibernate :
           ########################################
           # true, getOne 后加载的引用实体不用再查下database，避免出现no session 错误
           ########################################
           enable_lazy_load_no_trans: true
           dialect : org.hibernate.dialect.MySQL5Dialect
  batch : 
      job :
         enabled : false
      table-prefix : BATCH_
###################################################################
  security:
    user:
      name: admin
      password: 123456
  #freemarker的viewResolver没有在spring-cloud-netflix-eureka-server-1.3.1.RELEASE.jar中找到模板
  freemarker:
     prefer-file-system-access: false
###############################################################################
# Eureka gui will be displayed
###############################################################################
security:
    basic:
      enabled: false  # 开启基于HTTP basic的认证
context : 
      listener : 
         classes : com.unieap.base.ApplicationEventListener
#通过HTTP发送shutdown信号
management:
   endpoints: 
      web:
         exposure:
           include: '*'
   endpoint:
      #启用shutdown   
      shutdown: 
         enabled: true
         #禁用密码验证
         sensitive: false
      health:
         show-details: always