//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.06 at 06:59:23 PM CST 
//


package com.easy.unieap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.easy.unieap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BizHandle_QNAME = new QName("http://www.unieap.easy.com", "bizHandle");
    private final static QName _BizHandleResponse_QNAME = new QName("http://www.unieap.easy.com", "bizHandleResponse");
    private final static QName _QueryInfo_QNAME = new QName("http://www.unieap.easy.com", "queryInfo");
    private final static QName _QueryInfoResponse_QNAME = new QName("http://www.unieap.easy.com", "queryInfoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.easy.unieap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BizHandle }
     * 
     */
    public BizHandle createBizHandle() {
        return new BizHandle();
    }

    /**
     * Create an instance of {@link BizHandleResponse }
     * 
     */
    public BizHandleResponse createBizHandleResponse() {
        return new BizHandleResponse();
    }

    /**
     * Create an instance of {@link QueryInfo }
     * 
     */
    public QueryInfo createQueryInfo() {
        return new QueryInfo();
    }

    /**
     * Create an instance of {@link QueryInfoResponse }
     * 
     */
    public QueryInfoResponse createQueryInfoResponse() {
        return new QueryInfoResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BizHandle }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BizHandle }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.unieap.easy.com", name = "bizHandle")
    public JAXBElement<BizHandle> createBizHandle(BizHandle value) {
        return new JAXBElement<BizHandle>(_BizHandle_QNAME, BizHandle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BizHandleResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BizHandleResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.unieap.easy.com", name = "bizHandleResponse")
    public JAXBElement<BizHandleResponse> createBizHandleResponse(BizHandleResponse value) {
        return new JAXBElement<BizHandleResponse>(_BizHandleResponse_QNAME, BizHandleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.unieap.easy.com", name = "queryInfo")
    public JAXBElement<QueryInfo> createQueryInfo(QueryInfo value) {
        return new JAXBElement<QueryInfo>(_QueryInfo_QNAME, QueryInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.unieap.easy.com", name = "queryInfoResponse")
    public JAXBElement<QueryInfoResponse> createQueryInfoResponse(QueryInfoResponse value) {
        return new JAXBElement<QueryInfoResponse>(_QueryInfoResponse_QNAME, QueryInfoResponse.class, null, value);
    }

}
