package com.unieap.base.pojo;
// default package
// Generated 2015-8-8 16:02:23 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;


/**
 * ExLog generated by hbm2java
 */
@Entity
@Table(name = "mdm_exclog", catalog = "unieap")
public class MdmExclog implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false, length = 16)
	private Long id;
	@Column(name = "operatorName", nullable = false, length = 256)
	private String operatorName;
	@Column(name = "operationDate", nullable = false)
	private Date operationDate;
	@Column(name = "exType", nullable = false, length = 32)
	private String exType;
	@Column(name = "bizModule", nullable = false, length = 32)
	private String bizModule;
	@Column(name = "exCode", nullable = false, length = 32)
	private String exCode;
	@Column(name = "exInfo", nullable = false, length = 32)
	private String exInfo;
	@Lob
	@Column(name = "exTracking", nullable = true)
	private byte[] exTracking;
	@Column(name = "tenantId", nullable = false, length = 16)
	private Long tenantId;

	public MdmExclog() {
	}

	public MdmExclog(Long id, String operatorName, Date operationDate, String exType, String bizModule,Long tenantId) {
		this.id = id;
		this.operatorName = operatorName;
		this.operationDate = operationDate;
		this.exType = exType;
		this.bizModule = bizModule;
		this.tenantId = tenantId;
	}

	public MdmExclog(Long id, String operatorName, Date operationDate, String exType, String bizModule, String exCode,
			String exInfo, byte[] exTracking,Long tenantId) {
		this.id = id;
		this.operatorName = operatorName;
		this.operationDate = operationDate;
		this.exType = exType;
		this.bizModule = bizModule;
		this.exCode = exCode;
		this.exInfo = exInfo;
		this.exTracking = exTracking;
		this.tenantId = tenantId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	public Date getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	public String getExType() {
		return this.exType;
	}

	public void setExType(String exType) {
		this.exType = exType;
	}

	public String getBizModule() {
		return this.bizModule;
	}

	public void setBizModule(String bizModule) {
		this.bizModule = bizModule;
	}

	public String getExCode() {
		return this.exCode;
	}

	public void setExCode(String exCode) {
		this.exCode = exCode;
	}

	public String getExInfo() {
		return this.exInfo;
	}

	public void setExInfo(String exInfo) {
		this.exInfo = exInfo;
	}

	public byte[] getExTracking() {
		return this.exTracking;
	}

	public void setExTracking(byte[] exTracking) {
		this.exTracking = exTracking;
	}

	public Long getTenantId() {
		return tenantId;
	}

	public void setTenantId(Long tenantId) {
		this.tenantId = tenantId;
	}

}
