package com.unieap.base.pojo;
// default package
// Generated 2015-8-8 16:02:23 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * ExLog generated by hbm2java
 */
@Entity
@Table(name = "mdm_file_task", catalog = "unieap")
public class MdmFileTask implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false, length = 16)
	private Long id;
	@Column(name = "taskType", nullable = false, length = 256)
	private String taskType;
	@Column(name = "taskName", nullable = false, length = 256)
	private String taskName;
	@Column(name = "handlerName", nullable = false, length = 45)
	private String handlerName;
	@Column(name = "fileIds", nullable = false, length = 512)
	private String fileIds;
	@Column(name = "parameters", nullable = false, length = 1024)
	private String parameters;
	@Column(name = "executeStatus", nullable = false, length = 45)
	private String executeStatus;
	@Column(name = "createDate", nullable = false)
	private Date createDate;
	@Column(name = "createBy", nullable = false, length = 32)
	private String createBy;
	@Column(name = "executeDate", nullable = false)
	private Date executeDate;
	@Column(name = "remark", nullable = false, length = 512)
	private String remark;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public String getTaskType() {
		return taskType;
	}
	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}
	public String getTaskName() {
		return taskName;
	}
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}
	public String getHandlerName() {
		return handlerName;
	}
	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}
	public String getParameters() {
		return parameters;
	}
	public void setParameters(String parameters) {
		this.parameters = parameters;
	}
	public String getExecuteStatus() {
		return executeStatus;
	}
	public void setExecuteStatus(String executeStatus) {
		this.executeStatus = executeStatus;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	public Date getExecuteDate() {
		return executeDate;
	}
	public void setExecuteDate(Date executeDate) {
		this.executeDate = executeDate;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getFileIds() {
		return fileIds;
	}
	public void setFileIds(String fileIds) {
		this.fileIds = fileIds;
	}

	
}
