package com.unieap.base.vo;
// Generated 2015-10-24 14:14:02 by Hibernate Tools 4.3.1

/**
 * ErrorCode generated by hbm2java
 */
public class MessageVO extends BaseVO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String value;
	private String appName;
	private String language;
	private String category;
	private String remark;
	public int getId() {
		return id;
	}
	public String getName() {
		return name;
	}
	public String getValue() {
		return value;
	}
	public String getAppName() {
		return appName;
	}
	public String getLanguage() {
		return language;
	}
	public String getRemark() {
		return remark;
	}
	public void setId(int id) {
		this.id = id;
	}
	public void setName(String name) {
		this.name = name;
	}
	public void setValue(String value) {
		this.value = value;
	}
	public void setAppName(String appName) {
		this.appName = appName;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	

}
